/* Profanity Configuration

   Word lists for content moderation in the chat.

   Two severity tiers:
   - SEVERE: Slurs, hate speech, extreme vulgarity → hard block
   - MILD: Common profanity, crude language → auto-censor to asterisks

   Two languages: Dutch + English

   Update this file to add/remove words as your community needs evolve.
*/

class ProfanityConfig {
  ProfanityConfig._();

  // ── SEVERE WORDS ─────────────────────────────────────────────────────────
  //
  // These trigger instant message rejection. Include slurs, hate speech,
  // extreme sexual/violent language, and anything that should never appear.

  static const List<String> severeWordsDutch = [
    // Racial/ethnic slurs
    'kut-marokkaan',
    'mof',
    'moffrika',
    'mongool',
    'mongooltje',
    'neger',
    'nigger',
    'nikker',
    'nikkers',
    'niksnut',
    'nikkerslet',
    
    // Disease-based slurs (extremely offensive in Dutch)
    // Both standalone and compound forms
    'kanker',
    'kankerhoer',
    'kankerhond',
    'kankerlijer',
    'kankerlijder',
    'kankernicht',
    'kankerslet',
    'tering',
    'teringlijer',
    'teringlijder',
    'tyfus',
    'tyfuslijer',
    'pest',
    'pestlijder',
    'pleuris',
    'pleurislijder',
    'kolere',
    'pokken',
    
    // Extreme sexual/violent
    'hoerenjong',
    'hoerenkind',
    'hoerenzoon',
    'kutwijf',
    'kutvent',
    'klootzak',
    'verkrachten',
    
    // Homophobic slurs
    'flikker',
    'nicht',
    'noppeshoer',
    'potje',
    
    // Ableist slurs
    'debiel',
    'randdebiel',
    'reetridder',
  ];

  static const List<String> severeWordsEnglish = [
    // Racial/ethnic slurs
    'nigger',
    'nigga',
    'chink',
    'spic',
    'kike',
    'wetback',
    'raghead',
    'towelhead',
    'gook',
    'coon',
    'beaner',
    'paki',
    
    // Homophobic slurs
    'faggot',
    'fag',
    'dyke',
    'tranny',
    
    // Ableist slurs
    'retard',
    'retarded',
    'spastic',
    
    // Extreme sexual/violent
    'rape',
    'molest',
    'rapist',
    
    // Hate speech patterns
    'kill yourself',
    'kys',
  ];

  // ── MILD WORDS ───────────────────────────────────────────────────────────
  //
  // These get auto-censored to asterisks but the message still goes through.
  // Common swear words, crude language that's vulgar but not hateful.

  static const List<String> mildWordsDutch = [
    // Common profanity
    'kut',
    'kutstreek',
    'kuttenkop',
    'lul',
    'lulhannes',
    'lummel',
    'eikel',
    'klote',
    'kloten',
    'klooien',
    'klojo',
    'kluns',
    
    // Religious/blasphemy
    'godverdomme',
    'godverdamme',
    'verdomme',
    'verdorie',
    'jezus',
    'christus',
    
    // Anatomical
    // Note: 'gat' removed - too many false positives with 'gaat' (goes)
    'pik',
    'piemel',
    'kont',
    'reet',
    'eendenkont',
    'hol',
    'aars',
    'zak',
    
    // Common insults
    // Note: 'hoer' removed - false positives with 'hoe' (how). Compounds like 'hoerenzoon' still in severe.
    'stom',
    'idioot',
    'dwaas',
    'imbeciel',
    'sufkop',
    'sukkel',
    'eikel',
    'hufter',
    'huffter',
    'muts',
    'knurft',
    'knuppel',
    'lomperd',
    'lummel',
    'mafketel',
    'mafkikker',
    'pannenkoek',
    'pummel',
    'puist',
    'schoft',
    'schavuit',
    'smeerlap',
    'smeerpijp',
    'sloerie',
    'slet',
    'trut',
    'wijf',
    'zeikerd',
    'zeur',
    
    // Sexual terms (mild)
    'pijpen',
    'aftrekken',
    'beffen',
    'neuken',
    'rukken',
    'wippen',
    'vingeren',
    'zuigen',
    
    // Scatological
    'schijt',
    'schijten',
    'poep',
    'poepen',
    'stront',
    'drol',
    'kak',
    'kakken',
    'zeiken',
    'zeiker',
    'pis',
    'pissen',
    
    // Milder insults  
    'aasgier',
    'aap',
    'baviaan',
    'dombo',
    'domoor',
    'droplul',
    'druiloor',
    'etter',
    'etterbak',
    'galbak',
    'gladakker',
    'greppeldel',
    'hark',
    'heks',
    'hoerig',
    'kaas',
    'kaffer',
    'kalf',
    'kinkel',
    'koekwaus',
    'koekwous',
    'kwal',
    'labbekak',
    'lafaard',
    'lafbek',
    'lelijke',
    'leuter',
    'loser',
    'macho',
    'malloot',
    'matje',
    'minkukel',
    'mispunt',
    'naarling',
    'nul',
    'oen',
    'olla',
    'onbenul',
    'pagadder',
    'paljas',
    'palurk',
    'pestkop',
    'pestvent',
    'pig',
    'pinda',
    'plug',
    'pot',
    'raas',
    'ranzig',
    'rat',
    'rotzak',
    'rugzak',
    'schele',
    'schertsfiguur',
    'schijt',
    'schijnheilige',
    'schijtebroek',
    'schijthuis',
    'schobbejak',
    'schoft',
    'schooier',
    'schorem',
    'schurftig',
    'slaaf',
    'slappeling',
    'slapjanus',
    'slome',
    'slons',
    'smeerpoes',
    'smeerpoets',
    'smerig',
    'snertvent',
    'stinkerd',
    'sufferd',
    'sul',
    'teef',
    'trieste',
    'trutje',
    'waanzinnige',
    'walgelijk',
    'warhoofd',
    'warhoofd',
    'watje',
    'zak',
    'zakkenwasser',
    'zeur',
    'zeikous',
    'zwijn',
    
    // From Wiktionary list (A-Z selection)
    'aambeiienlikker',
    'aapmens',
    'aardappel',
    'aarstulp',
    'aasgie',
    'achterlader',
    'adder',
    'addergebroed',
    'angsthaas',
    'apejong',
    'apenkont',
    'appelflap',
    'autist',
    'babi',
    'babok',
    'badgast',
    'baggerduiker',
    'bakvis',
    'bal',
    'baliekluiver',
    'bandiet',
    'bangerd',
    'bangerik',
    'bangeschijter',
    'barslet',
    'bedrijfspoedel',
    'beheime',
    'belhamel',
    'bermslet',
    'biljartbal',
    'bitch',
    'blaag',
    'bleekscheet',
    'bliksemstraal',
    'bloedlier',
    'boef',
    'boeler',
    'boer',
    'boerenhufter',
    'boerenkaffer',
    'boerenkarhengst',
    'boerenkinkel',
    'boerenpummel',
    'boerin',
    'bokkelul',
    'bokkenrijder',
    'bokkenlul',
    'booswicht',
    'bosaap',
    'bosneuker',
    'botterik',
    'bouwdoos',
    'braadvarken',
    'breezerslet',
    'brilaap',
    'brillenjood',
    'brilsmurf',
    'broodaap',
    'bruinwerker',
    'bruut',
    'bulderbast',
    'charlatan',
    'choco',
    'chocoladehoer',
    'chocoladesnol',
    'cijferneuker',
    'coronalijer',
    'cretin',
    'criticaster',
    'dagdief',
    'del',
    'deugdief',
    'deuggleuf',
    'deugkneus',
    'diepduiker',
    'diepdoos',
    'dirkdoos',
    'doolhof',
    'doos',
    'dreuzel',
    'droplul',
    'druifluis',
    'druiloor',
    'duimendraaier',
    'duimendraier',
    'ectoplaama',
    'eend',
    'ezel',
    'ezelsveulen',
    'fielt',
    'flapdrol',
    'flapdrool',
    'fleer',
    'flessentrekker',
    'flierefluter',
    'foefkop',
    'fransoos',
    'gaapsnaas',
    'galgenbrok',
    'gangster',
    'gannef',
    'geboefte',
    'geit',
    'geitenbreier',
    'geitenneuker',
    'gemenerik',
    'gespuis',
    'geteisem',
    'gladakker',
    'gleuf',
    'gluiper',
    'gluiperd',
    'gluipsnor',
    'gortenteller',
    'gratenbaal',
    'gratenkut',
    'greppeldel',
    'grobbejanus',
    'haai',
    'haaibaai',
    'halvezool',
    'halvezole',
    'hapsnurker',
    'harpij',
    'hazenhart',
    'heaumeau',
    'heaumeaux',
    'heihaas',
    'heikneuter',
    'heks',
    'hersenlijer',
    'hielenlikker',
    'hockeytrut',
    'hockeytut',
    'hoerenjager',
    'homo',
    'hond',
    'hondenjul',
    'hondenneuker',
    'hork',
    'huichelaar',
    'huppelkut',
    'huzarenhoop',
    'janhagel',
    'jeannette',
    'kaas',
    'kaashoer',
    'kaaskop',
    'kaffer',
    'kakhuis',
    'kakkerlak',
    'kakmadam',
    'kakmaker',
    'kamelenneuker',
    'kamerolifant',
    'kankerthoer',
    'kapsoneslijer',
    'karhengst',
    'karonje',
    'karpatenkop',
    'kees',
    'keilef',
    'kelerelijer',
    'keutelkut',
    'kiendop',
    'kinkel',
    'kip',
    'klabak',
    'klafte',
    'klapkut',
    'klapluis',
    'klaplul',
    'klapperaap',
    'klavierridder',
    'klere',
    'klier',
    'kloefkapper',
    'klooihannes',
    'kloot',
    'klootviool',
    'kloothommel',
    'knijpkont',
    'koekwaus',
    'koeskoesveter',
    'koffieboon',
    'kokosmaakroon',
    'kontkruiper',
    'kontlikker',
    'kontneuker',
    'kreng',
    'kriel',
    'krielkip',
    'krijslijer',
    'kroeskop',
    'kruimelbuik',
    'kruiper',
    'kruk',
    'kwal',
    'kwakzalver',
    'labbekak',
    'labrat',
    'lafaard',
    'lafbek',
    'lammeling',
    'lamstraal',
    'lamzak',
    'lanterfanter',
    'leegloper',
    'lelijkerd',
    'lichtekooi',
    'lijer',
    'linkmiegel',
    'lol',
    'lollardisch',
    'lomperd',
    'lomperik',
    'loser',
    'luibak',
    'luibuis',
    'luilak',
    'luiskop',
    'luiwammes',
    'macaronivreter',
    'maffer',
    'mafferik',
    'mafketel',
    'mafkikker',
    'makaak',
    'malloot',
    'matennaaier',
    'mie',
    'miet',
    'mietje',
    'mispruim',
    'modderduivel',
    'moederskindje',
    'moederskindjes',
    'palurk',
    'pampaboy',
    'paplap',
    'pasjakroet',
    'patjakker',
    'pedo',
    'pekelhoer',
    'pepermuntvreter',
    'pestlijder',
    'pestvent',
    'pigmentvreter',
    'pijpendraaier',
    'pleurislijer',
    'ploert',
    'plug',
    'plucheplakker',
    'plurk',
    'poepchinees',
    'pokkenlijer',
    'pokkenwijf',
    'polak',
    'politiemuts',
    'pommel',
    'populist',
    'pothoer',
    'puistenkop',
    'pukkelbek',
    'pummel',
    'pussy',
    'raas',
    'rekel',
    'retenlikker',
    'roetmop',
    'rotkerel',
    'rotmof',
    'rotvent',
    'rugridder',
    'ruigpoot',
    'sakkers',
    'sambalburger',
    'sambalvreter',
    'schaapskop',
    'schansloper',
    'schavuit',
    'schele',
    'schelm',
    'scherrelmorrie',
    'schijerd',
    'schijthoofd',
    'schijtlaars',
    'schijtlijier',
    'schijtluis',
    'schimmelkut',
    'schlemiel',
    'schobbejak',
    'schoelje',
    'schoft',
    'schoothond',
    'schorem',
    'schorremorrie',
    'schorriemorrie',
    'schuinsmarcheerder',
    'schurftkop',
    'schurk',
    'schuurmeid',
    'secreto',
    'sekreet',
    'slampamper',
    'slapjanus',
    'slet',
    'slettenbak',
    'slijmbal',
    'slijmerd',
    'sloerie',
    'slomerik',
    'smeerkaans',
    'smeerkees',
    'smeerlap',
    'smeerpijp',
    'smeerpoes',
    'smeerpoets',
  ];

  static const List<String> mildWordsEnglish = [
    'fuck',
    'fucking',
    'fucked',
    'fucker',
    'shit',
    'shit',
    'shitty',
    'damn',
    'damned',
    'dammit',
    'hell',
    'ass',
    'asshole',
    'bitch',
    'bastard',
    'crap',
    'piss',
    'pissed',
    'dick',
    'cock',
    'pussy',
    'whore',
    'slut',
    'douche',
    'douchebag',
    'twat',
    'wanker',
    'bollocks',
    'bugger',
    'arse',
    'arsehole',
    'prick',
    'tosser',
    'git',
    'sod',
    'bloody',
    'cunt',
  ];

  // ── COMBINED LISTS ───────────────────────────────────────────────────────

  static List<String> get allSevereWords => [
    ...severeWordsDutch,
    ...severeWordsEnglish,
  ];

  static List<String> get allMildWords => [
    ...mildWordsDutch,
    ...mildWordsEnglish,
  ];
}