name: radio_apollo
description: "The radio apollo app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  cloud_firestore: ^5.0.0
  firebase_core: ^3.0.0
  http: ^1.2.0
  flutter:
    sdk: flutter
  just_audio: ^0.9.36
  audio_service: ^0.18.12
  audio_session: ^0.1.16
  shared_preferences: ^2.3.0   # NEW — stores username locally on device

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/images/Logo/
    - assets/images/Background/
  uses-material-design: true