name: radio_apollo
description: "The radio apollo app."
publish_to: 'none'

version: 1.7.7+25

environment:
  sdk: ^3.11.1

dependencies:
  cloud_firestore: 6.2.0
  firebase_core: 4.6.0
  http: ^1.2.0
  flutter:
    sdk: flutter
  just_audio: ^0.9.36
  audio_service: ^0.18.12
  audio_session: ^0.1.16
  shared_preferences: ^2.3.0 
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.0.0
  flutter_chrome_cast: ^1.4.5
  url_launcher: ^6.2.0
  package_info_plus: ^8.0.0
  firebase_app_check: 0.4.2
  firebase_messaging: 16.1.3
  flutter_local_notifications: ^19.4.0
  app_settings: ^7.0.0
  firebase_crashlytics: 5.1.0
  add_2_calendar: ^3.0.1
  in_app_update: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

flutter:
  assets:
    - assets/images/Logo/
    - assets/images/Background/
    - assets/images/AppLogo/
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/AppLogo/app_logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/AppLogo/app_logo.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/AppLogo/app_logo.png
  android: true
  ios: true