// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2nL8ohN0dwY7e25ZrV0mWPEswWRdQhPU',
    appId: '1:524210502074:web:2d2f32ffaf23c2ad2b8583',
    messagingSenderId: '524210502074',
    projectId: 'radio-apollo-ca2ee',
    authDomain: 'radio-apollo-ca2ee.firebaseapp.com',
    storageBucket: 'radio-apollo-ca2ee.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxBGSAOkgne6_8mszBMqwiKMvSJ4-PDMI',
    appId: '1:524210502074:ios:37b8a3c813745e412b8583',
    messagingSenderId: '524210502074',
    projectId: 'radio-apollo-ca2ee',
    storageBucket: 'radio-apollo-ca2ee.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2nL8ohN0dwY7e25ZrV0mWPEswWRdQhPU',
    appId: '1:524210502074:web:7a37b5b73cefbb482b8583',
    messagingSenderId: '524210502074',
    projectId: 'radio-apollo-ca2ee',
    authDomain: 'radio-apollo-ca2ee.firebaseapp.com',
    storageBucket: 'radio-apollo-ca2ee.firebasestorage.app',
  );
}
