// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmJ4n2iQzNsRqMl62tu_DgSYTPX6ZiT6E',
    appId: '1:1086114344104:web:1f406a563a042f0d0e269d',
    messagingSenderId: '1086114344104',
    projectId: 'radio-apollo-90693',
    authDomain: 'radio-apollo-90693.firebaseapp.com',
    databaseURL:
        'https://radio-apollo-90693-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'radio-apollo-90693.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3HVP4-KLyWUGpuRbyy96KN--3A92lbCw',
    appId: '1:1086114344104:android:68f2f4083cd7bdd50e269d',
    messagingSenderId: '1086114344104',
    projectId: 'radio-apollo-90693',
    databaseURL:
        'https://radio-apollo-90693-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'radio-apollo-90693.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFeyQIT0FlZDnLPz2ItIEIhpAZZmKR968',
    appId: '1:1086114344104:ios:ac35dd4997b1245e0e269d',
    messagingSenderId: '1086114344104',
    projectId: 'radio-apollo-90693',
    databaseURL:
        'https://radio-apollo-90693-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'radio-apollo-90693.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFeyQIT0FlZDnLPz2ItIEIhpAZZmKR968',
    appId: '1:1086114344104:ios:ac35dd4997b1245e0e269d',
    messagingSenderId: '1086114344104',
    projectId: 'radio-apollo-90693',
    databaseURL:
        'https://radio-apollo-90693-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'radio-apollo-90693.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmJ4n2iQzNsRqMl62tu_DgSYTPX6ZiT6E',
    appId: '1:1086114344104:web:5c51bad142dfaf9b0e269d',
    messagingSenderId: '1086114344104',
    projectId: 'radio-apollo-90693',
    authDomain: 'radio-apollo-90693.firebaseapp.com',
    databaseURL:
        'https://radio-apollo-90693-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'radio-apollo-90693.firebasestorage.app',
  );
}
